name: phidl
channels:
  - enneamer
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blas
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cython
  - decorator
  - ete3
  - fire
  - freetype
  - future
  - gettext
  - graphite2
  - hyperopt
  - icu
  - intel-openmp
  - jpeg
  - libffi
  - libiconv
  - libpng
  - libtiff
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - mkl
  - mkl_fft
  - mkl_random
  - networkx
  - ninja
  - numpy
  - numpy-base
  - pcre
  - pip
  - pixman
  - pthread-stubs
  - pycparser
  - pymongo
  - pyqt
  - python
  - pyyaml
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zlib
  - glib
  - harfbuzz
  - pytorch
  - pango
  - fontconfig
  - logbook
  - qt
  - pip:
    - adabound
